#if !canImport(ObjectiveC)
import XCTest

extension CodableContextTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CodableContextTests = [
        ("enum__with_enum_case_key__codes_value_with_associated_values", enum__with_enum_case_key__codes_value_with_associated_values),
        ("enum__with_enum_case_key__can_t_use_value_with_unnamed_associated_values", enum__with_enum_case_key__can_t_use_value_with_unnamed_associated_values),
        ("enum__with_enum_case_key__can_t_use_value_with_mixed_associated_values", enum__with_enum_case_key__can_t_use_value_with_mixed_associated_values),
        ("enum__with_enum_case_key__codes_value_without_associated_values", enum__with_enum_case_key__codes_value_without_associated_values),
        ("enum__without_enum_case_key__codes_value_with_associated_values", enum__without_enum_case_key__codes_value_with_associated_values),
        ("enum__without_enum_case_key__codes_value_with_unnamed_associated_values", enum__without_enum_case_key__codes_value_with_unnamed_associated_values),
        ("enum__without_enum_case_key__can_t_use_value_with_mixed_associated_values", enum__without_enum_case_key__can_t_use_value_with_mixed_associated_values),
        ("enum__without_enum_case_key__codes_value_without_assoicated_values", enum__without_enum_case_key__codes_value_without_assoicated_values),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(CodableContextTests.__allTests__CodableContextTests),
    ]
}
#endif
