author: Krzysztof Zabłocki
author_url: https://twitter.com/merowing_
module: Sourcery
sourcekitten_sourcefile: docs.json 
module_version: 0.6.0
github_url: https://github.com/krzysztofzablocki/Sourcery
copyright: 'Copyright © 2016 Pixle. All rights reserved.'
readme: About.md
documentation: guides/*.md
exclude: 
  - SourceryFramework/Utils/*
  - SourceryFramework/CodeGenerated/*

custom_categories:
  - name: Guides
    children:
      - Installing
      - Usage
      - Writing templates

  - name: Examples
    children:
      - Equatable
      - Hashable
      - Enum cases
      - Lenses
      - Mocks
      - Diffable
      - LinuxMain
      - Decorator

  - name: Types
    children:
      - Types 
      - Type
      - Protocol
      - Class
      - Struct
      - Enum
      - EnumCase
      - AssociatedValue
      - Variable 
      - Method
      - MethodParameter
      - TypeName
      - TupleType
      - TupleElement
      - ArrayType
      - DictionaryType
      - ClosureType
      - Attribute
