import Quick
import Nimble
@testable import Sourcery
@testable import SourceryFramework

class VerifierSpec: QuickSpec {
    override func spec() {
        describe("Verifier") {
            it("allows empty strings") {
                expect(Verifier.canParse(content: "")).to(equal(Verifier.Result.approved))
            }

            it("rejects files generated by Sourcery") {
                let content = Sourcery.generationMarker + "\n something\n is\n there"

                expect(Verifier.canParse(content: content)).to(equal(Verifier.Result.isCodeGenerated))
            }

            it("rejects file containing conflict marker") {
                let content = ["\n<<<<<\n", "\n>>>>>\n"]

                content.forEach { expect(Verifier.canParse(content: $0)).to(equal(Verifier.Result.containsConflictMarkers)) }
            }
        }
    }
}
