version: 2

jobs:
  test:
    macos:
      xcode: "13.3.0"
    environment:
      BUNDLE_JOBS: 3
      BUNDLE_RETRY: 3
      BUNDLE_PATH: vendor/bundle
    shell: /bin/bash --login -eo pipefail
    steps:
      - checkout
      - run: sudo defaults write com.apple.dt.Xcode IDEPackageSupportUseBuiltinSCM YES
      - run: rm ~/.ssh/id_rsa || true
      - run: for ip in $(dig @8.8.8.8 bitbucket.org +short); do ssh-keyscan bitbucket.org,$ip; ssh-keyscan $ip; done 2>/dev/null >> ~/.ssh/known_hosts || true 
      - run: for ip in $(dig @8.8.8.8 github.com +short); do ssh-keyscan github.com,$ip; ssh-keyscan $ip; done 2>/dev/null >> ~/.ssh/known_hosts || true
      - run: brew update 1> /dev/null 2> /dev/null
      - run: brew install sourcekitten
      - run: brew install coreutils
      - run: echo "ruby-3.0.0" > ~/.ruby-version
      - run: bundle install
      - run: bundle exec rake validate_docs
      - run: bundle exec danger || true
      - run: set -o pipefail
      - run: bundle exec rake build
      - run: bundle exec rake tests

workflows:
  version: 2
  build-test:
    jobs:
      - test
