machine:
  xcode:
    version: 9.3.0
  environment:
    XCODE_WORKSPACE: Sourcery.xcworkspace
    XCODE_PROJECT: Sourcery.xcodeproj
    XCODE_SCHEME: Sourcery
  post:
      - ln -s /Applications/Xcode-8.3.app /Applications/Xcode.app
      - brew install sourcekitten

test:
  pre:
      - rake validate_docs
      - bundle exec danger || true
  override:
      - set -o pipefail
      - xcodebuild -workspace "$XCODE_WORKSPACE" -scheme "$XCODE_SCHEME" ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO build | xcpretty
      - xcodebuild -workspace "$XCODE_WORKSPACE" -scheme "$XCODE_SCHEME" ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO test | tee $CIRCLE_ARTIFACTS/xcode_raw.log | xcpretty --color --report junit --output $CIRCLE_TEST_REPORTS/xcode/results.xml
      - swift build
  post:
    - bundle exec slather coverage --scheme "$XCODE_SCHEME" --workspace "$XCODE_WORKSPACE" --output-directory $CIRCLE_ARTIFACTS --binary-basename SourceryRuntime --binary-basename Sourcery --cobertura-xml Sourcery.xcodeproj
    - bash <(curl -s https://codecov.io/bash) -f $CIRCLE_ARTIFACTS/cobertura.xml -X coveragepy -X gcov -X xcode
