#if !canImport(ObjectiveC)
import XCTest

extension TemplatesTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TemplatesTests = [
        ("AutoCases_template__generates_expected_code", AutoCases_template__generates_expected_code),
        ("AutoEquatable_template__generates_expected_code", AutoEquatable_template__generates_expected_code),
        ("AutoHashable_template__generates_expected_code", AutoHashable_template__generates_expected_code),
        ("AutoLenses_template__generates_expected_code", AutoLenses_template__generates_expected_code),
        ("AutoMockable_template__generates_expected_code", AutoMockable_template__generates_expected_code),
        ("LinuxMain_template__generates_expected_code", LinuxMain_template__generates_expected_code),
        ("AutoCodable_template__generates_expected_code", AutoCodable_template__generates_expected_code),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(TemplatesTests.__allTests__TemplatesTests),
    ]
}
#endif
