name: Bump Homebrew formula

on:
  workflow_dispatch:
    inputs:
      tag-name:
        description: 'The git tag name to bump the formula to'
        required: true

jobs:
  homebrew:
    name: Bump Homebrew formula
    runs-on: macos-13
    steps:
      - uses: mislav/bump-homebrew-formula-action@v3
        with:
          formula-name: sourcery
          tag-name: ${{ github.event.inputs.tag-name }}
        env:
          COMMITTER_TOKEN: ${{ secrets.HOMEBREW_COMMITTER_TOKEN }}