name: Release Build for Linux

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Ref to build (branch, tag or SHA)'
        required: false
        default: 'master'
  pull_request:
    branches:
      [ master ]

jobs:
  build:
    name: Build Sourcery for Ubuntu (latest)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.ref }}
      - name: Install dependencies
        run:  |
            sudo apt install build-essential
      - name: Build it
        run: |
          swift build --configuration release --static-swift-stdlib --enable-dead-strip
          SWIFTFORMAT_BIN_PATH=`swift build --configuration release --show-bin-path`
          mv $SWIFTFORMAT_BIN_PATH/sourcery_ubuntu "${HOME}/sourcery_ubuntu"
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: sourcery_ubuntu
          path: ~/sourcery_ubuntu
          retention-days: 5
