name: release ubuntu

on:
  workflow_run:
    workflows: [test ubuntu]
    types:
      - completed
  workflow_dispatch:
    inputs:
      ref:
        description: 'Ref to build (branch, tag or SHA)'
        required: false
        default: 'master'
  pull_request:
    branches:
      - master
  push:
    tags:
      - '*'

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Build Sourcery for Ubuntu (latest)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.ref }}
      - name: Setup Swift
        uses: swift-actions/setup-swift@v1.26.0
        with:
          swift-version: "5.9.2"
      - name: Build it
        run: |
          BUILD_DIR='${HOME}/build/'
          swift build --disable-sandbox -c release --build-path $BUILD_DIR
          mv "${BUILD_DIR}x86_64-unknown-linux-gnu/release/sourcery" "${HOME}/sourcery"
          
          UNAME=$(uname -m)
          CODENAME=$(lsb_release -c -s)
          DESCRIPTION=$(lsb_release -d -s | sed "s/ /-/g" | sed "s/./\L&/g")
          SUFFIX=$DESCRIPTION-$CODENAME-$UNAME
          TAG=$GITHUB_REF_NAME
          FILENAME=sourcery-${TAG}-${SUFFIX}.tar.xz
          tar -zcvf $FILENAME $CLI_DIR
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: $FILENAME
          path: ~/$FILENAME
          retention-days: 5
