# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: test ubuntu

on:
  workflow_call:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref_type != 'tag' }}

jobs:
  linux_build:
    runs-on: ubuntu-22.04
    steps:
    - name: Setup Swift
      uses: YOCKOW/Action-setup-swift@main
      with:
        swift-version: "5.9.2"
    - name: Get swift version
      run: swift --version
    - uses: actions/checkout@v3
    - name: Run tests
      run: swift test
